services:
  - type: web
    name: url-shortener-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: SECURITY_RATE_LIMIT_REQUESTS
        value: 100
      - key: SECURITY_RATE_LIMIT_PERIOD
        value: 3600
      - key: SECURITY_MAX_URL_LENGTH
        value: 2048
      - key: SECURITY_MAX_REQUEST_SIZE
        value: 1048576
      - key: SECURITY_IP_BLOCK_DURATION
        value: 3600
      - key: SECURITY_MAX_FAILED_REQUESTS
        value: 100
      - key: SECURITY_ALLOWED_SCHEMES
        value: '["http","https"]'
      - key: SECURITY_BLOCKED_DOMAINS
        value: '["localhost","127.0.0.1"]'
      - key: PYTHON_VERSION
        value: 3.8.0 